runtime: php55
api_version: 1

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true
- url: /css
  static_dir: css
- url: /javascript
  static_dir: javascript
- url: /fonts
  static_dir: fonts
# Serve php scripts.
- url: /vale-transporte/*
  script: vale-transporte.php
- url: /.*
  script: index.php